### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Mshu72** [Mshu72/protospace-40878#1]
https://protospace-40878.onrender.com

**Comment by ushi10** [comment]
@Mshu72 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

**プロトタイプ一覧表示機能**

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること。**
ログアウト状態の場合、詳細ページに遷移することができずトップページに戻されてしまいました。正しく遷移するよう修正をしましょう。
※詳細機能関連、詳細ページに関与する機能に関してはログアウト状態での挙動確認ができなかったため、次回以降に正しく遷移できるようになった後に確認いたします。

**ユーザー詳細機能**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
・コメント投稿者名をクリックすると特定のユーザー詳細画面にしか遷移できません。
・一覧ページの投稿者名をクリックするとトップページに戻されてしまいます。
それぞれ紐づくユーザー詳細ページへ正しく遷移できるよう修正しましょう。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@Mshu72 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
